[matfrost-mex]
git-tree-sha1 = "cf5dfd015a4e9236304a9dcf20297e943cc82a66"

    [[matfrost-mex.download]]
    sha256 = "1b99d8439ee36bea537a4e44c005ffc84d8adfae245676b56446bc5a5120bcda"
    url = "https://github.com/ASML-Labs/MATFrost.jl/releases/download/v0.7.0/matfrost-mex-v0.7.0.tar.gz"
