[matfrost-mex]
git-tree-sha1 = "3c64e8d2a2e9720abcb9edfdfae4bae4882d0d40"


    [[matfrost-mex.download]]
    sha256 = "26cea9dca7b408b84a9a66e0974aa121253d8c4314687d97bf5c9989e16479e1"
    url = "https://github.com/ASML-Labs/MATFrost.jl/releases/download/matfrost-mex-v0.4.0/matfrost-mex-v0.4.0-win-x64.tar.gz"
