name: "Release MATFrost MEX"

on:
  workflow_dispatch:
    inputs:
      matfrost-mex-version:
        required: true
        description: "MATFrost MEX version"
        default: "0.0.0+0"


jobs:
  build-mex-binary-and-test:
    name: Build MEX binaries and test
    uses: ./.github/workflows/run-tests-reusable.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        matlab-version: ['R2021b','R2025b']
        julia-version: ['1.7', '1.12']
        os: ['windows-latest', 'ubuntu-latest']
    with:
      os: ${{ matrix.os }}
      matlab-version: ${{ matrix.matlab-version }}
      mex-recompile: true
      julia-version: ${{ matrix.julia-version }}


  bundle-mex-binary:
    needs: build-mex-binary-and-test
    runs-on: ubuntu-latest
    name: Bundle MEX binaries
    steps:     
      - name: Download MEX artifacts
        uses: actions/download-artifact@v8
        with: 
          pattern: mexbin-*-R2021b-1.12
          path: mexbin
          merge-multiple: true
      - name: Display structure of downloade MEX binaries.
        run: ls -R mexbin
      - name: Bundle MEX binaries
        run: |
          tar -czvf matfrost-mex-v${{ inputs.matfrost-mex-version }}.tar.gz -C mexbin .
      
      - name: Upload mexbinaries release zipped
        uses: actions/upload-artifact@v7
        with: 
          path: matfrost-mex-v${{ inputs.matfrost-mex-version }}.tar.gz
          name: mexbin-release-zipped
  
      - name: Upload mexbinaries for testing
        uses: actions/upload-artifact@v7
        with: 
          path: mexbin/*
          name: mexbin

  test-mex-binaries-matlab-compatability:
    needs: bundle-mex-binary
    name: Test MATLAB compatability of MEX-binaries
    uses: ./.github/workflows/run-tests-reusable.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        matlab-version: ['R2021b','R2022a','R2022b','R2023a','R2023b','R2024a','R2024b','R2025a','R2025b']
        julia-version: ['1.12']
        os: ['windows-latest', 'ubuntu-latest']
    with:
      os: ${{ matrix.os }}
      matlab-version: ${{ matrix.matlab-version }}
      mex-recompile: false
      julia-version: ${{ matrix.julia-version }}
      julia-tests: false

  create-release:    
    needs: test-mex-binaries-matlab-compatability
    runs-on: ubuntu-latest
    name: Create the release
    steps:     
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download MEX artifacts
        uses: actions/download-artifact@v8
        with: 
          name: mexbin-release-zipped
      
      - uses: julia-actions/install-juliaup@v3
        with:
          channel: '1.12'
      
      - name: Integrate released Artifact in MATFrost package.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project="." "src/matfrostjuliacall/integrate_released_mexbinaries.jl" "${{ inputs.matfrost-mex-version }}" "matfrost-mex-v${{ inputs.matfrost-mex-version }}.tar.gz"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Artifacts.toml
          git commit -m "MATFrost MEX release v${{ inputs.matfrost-mex-version }}"
          git tag -a matfrost-mex-v${{ inputs.matfrost-mex-version }} -m "matfrost-mex-v${{ inputs.matfrost-mex-version }}"
          git push origin tag matfrost-mex-v${{ inputs.matfrost-mex-version }}
          sleep 5s

      - name: Release MEX binaries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create matfrost-mex-v${{ inputs.matfrost-mex-version }} --latest=false --title v${{ inputs.matfrost-mex-version }} matfrost-mex-v${{ inputs.matfrost-mex-version }}.tar.gz
          
