name: "Reusable workflow for running tests and building MEX" 

on:
  workflow_call:
    inputs:
      os:
        required: true
        description: "Operating system"
        default: "windows-latest"
        type: string
      matlab-version:
        required: true
        description: "MATLAB version"
        default: "R2022b"
        type: string
      julia-version:
        required: false
        description: "Julia version to test"
        default: "1.12"
        type: string
      mex-recompile:
        required: true
        description: "Recompile MEX binary"
        type: boolean
        default: true
      julia-tests:
        description: "Trigger Julia tests"
        type: boolean
        default: true      

permissions:
  actions: write
  contents: read

env:
  GCC_VERSION: 10

jobs:
  test:
    runs-on:  ${{ inputs.os }}
    name: ${{ inputs.os }}-${{ inputs.matlab-version }}-julia-${{ inputs.julia-version }}-recompile-${{ inputs.mex-recompile }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Juliaup
        uses: julia-actions/install-juliaup@05d98a2ef433ca0723a8221e38c4723ea92b0c5f # v3.1.4
        with:
          channel: ${{ inputs.julia-version }}

      - uses: julia-actions/cache@a45e8fa8be21c18a06b7177052533149e61e9b38 # v3.1.0
        with:
          cache-name: julia-cache;version=${{ inputs.julia-version }}
          include-matrix: false
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # v1.7.0

      - name: Test Julia
        if: ${{ inputs.julia-tests }}
        uses: julia-actions/julia-runtest@6e050c8013b833b1195105ff2fce9cd802f53271 # v1.12.0
          
      - name: Determine MATLAB product
        if: startsWith(inputs.os , 'windows')
        id: matlab-product
        shell: bash
        run: |
          version="${{ inputs.matlab-version }}"
          year=$(echo "$version" | sed 's/R\([0-9]\{4\}\)[ab]/\1/')
          if [ "$year" -gt 2023 ]; then
            echo "product=MATLAB_Support_for_MinGW-w64_C/C++/Fortran_Compiler" >> $GITHUB_OUTPUT
          else
            echo "product=MATLAB_Support_for_MinGW-w64_C/C++_Compiler" >> $GITHUB_OUTPUT
          fi

      - name: Install GCC on Linux
        if: ${{ startsWith(inputs.os , 'ubuntu') }}
        run: |
          sudo apt-get install g++-${{ env.GCC_VERSION }}

      - name: Configure compatible linux GCC compiler on Linux
        if: ${{ startsWith(inputs.os , 'ubuntu') }}
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 100
          sudo update-alternatives --config g++
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_VERSION} 100
          sudo update-alternatives --config gcc
          g++ --version
          gcc --version
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@2323adb8243827ea460b0def4c413545aaec46a9 # v3.0.2
        with:
          release: ${{ inputs.matlab-version }}
          products: ${{ steps.matlab-product.outputs.product }}
          cache: true

      - name: Download precompiled MEX artifacts
        if: ${{ !inputs.mex-recompile }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: 
          name: mexbin
          path: src/matlab/@matfrostjulia/private

       
      - name: Build MATFrost MEX
        uses: matlab-actions/run-command@75644028e1e2aa374bbfdc968a65718a178cc264 # v3.2.1
        if: ${{ inputs.mex-recompile }}
        with:
          command: addpath(genpath("src")) ; matfrostmake() ;
        
      - name: Run tests
        uses: matlab-actions/run-tests@71e231e8d51ae670c0bed0c756d832d648aab5d9 # v3.3.0
        env:
          JULIA_VERSIONS: ${{ inputs.julia-version }}
        with:
          source-folder: 'src/matlab'
          select-by-folder: 'test'
          strict: false
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: test-results/coverage.xml
      
      - name: Upload MEX binary
        if: ${{ inputs.mex-recompile }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with: 
          path: src/matlab/@matfrostjulia/private/matfrostjuliacall.mex*
          name: mexbin-${{ inputs.os }}-${{ inputs.matlab-version }}-${{ inputs.julia-version }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with: 
          path: test-results
          name: results-${{ inputs.os }}-${{ inputs.matlab-version }}-${{ inputs.julia-version }}-mex-recompile-${{ inputs.mex-recompile }}
