name: Run Tests Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
      - '.github/workflows/run-tests.yml'
      - '.github/workflows/run-tests-reusable.yml'
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
      - '.github/workflows/run-tests.yml'
      - '.github/workflows/run-tests-reusable.yml'

jobs:
  # Linux disabled due to incompatability. 
  #
  # ubuntu:
  #   uses: ./.github/workflows/run-tests-ubuntu.yml
  #   if: ${{ ((github.event_name == 'pull_request') && !github.event.pull_request.draft) || (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
  #   secrets: inherit
  windows:
    uses: ./.github/workflows/run-tests-windows.yml
    if: ${{ ((github.event_name == 'pull_request') && !github.event.pull_request.draft) || (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
    secrets: inherit
