name: "windows" 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-windows:
    uses: ./.github/workflows/run-tests-reusable.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        matlab-version: ['R2021b', 'R2022b', 'R2023b']
        julia-version: ['1.7', '1.8', '1.9', '1.10', '1.11']
    with:
      os: windows-latest
      matlab-version: ${{ matrix.matlab-version }}
      julia-version: ${{ matrix.julia-version }}
