name: Run Tests Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
      - '.github/workflows/run-tests.yml'
      - '.github/workflows/run-tests-reusable.yml'
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
      - '.github/workflows/run-tests.yml'
      - '.github/workflows/run-tests-reusable.yml'

jobs:
  test:
    uses: ./.github/workflows/run-tests-reusable.yml
    if: ${{ ((github.event_name == 'pull_request') && !github.event.pull_request.draft) || (github.event_name == 'push') }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04']
        matlab-version: ['R2021b', 'R2022b', 'R2023b']
        julia-version: ['1.7', '1.8', '1.9', '1.10']
    with:
      os: ${{ matrix.os }}
      matlab-version: ${{ matrix.matlab-version }}
      julia-version: ${{ matrix.julia-version }}
