name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.10']
        matlab-version: [R2022b]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.julia-version }}

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-version }}
          cache: true

      - run: |
          juliaup --version
          juliaup status
          julia --version
          julia +${{ matrix.julia-version }} -e "println(Base.VERSION)"
          juliaup add ${{ matrix.julia-version }}
          julia +${{ matrix.julia-version }} -e "println(Sys.BINDIR)"

      - name: Run statements
        uses: matlab-actions/run-command@v2
        with:
          command: |
            cd('src/matlab/private');
            shell('juliaup', '--version', echo=true);
            shell('juliaup', 'status', echo=true);
            shell('julia', '--version', echo=true);
            shell('julia', '+${{ matrix.julia-version }}', '-e' , '"println(Base.VERSION)"', echo=true);
            shell('juliaup', 'add', '${{ matrix.julia-version }}', echo=true)
            shell('julia', '+${{ matrix.julia-version }}', '-e',  '"println(Sys.BINDIR)"', echo=true);

      - name: Run tests
        uses: matlab-actions/run-tests@v2
        env:
          JULIA_VERSION: ${{ matrix.julia-version }}
        with:
          source-folder: 'src/matlab'
          select-by-folder: 'test'
          strict: false
          test-results-junit: test-reults/results.xml
          code-coverage-cobertura: test-reults/coverage.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          path: test-reults
