name: "windows" 

on:
  workflow_call:

jobs:
  test-windows:
    uses: ./.github/workflows/run-tests-reusable.yml
    if: ${{ ((github.event_name == 'pull_request') && !github.event.pull_request.draft) || (github.event_name == 'push') }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: windows-latest
        matlab-version: ['R2021b', 'R2022b', 'R2023b']
        julia-version: ['1.7', '1.8', '1.9', '1.10']
    with:
      os: ${{ matrix.os }}
      matlab-version: ${{ matrix.matlab-version }}
      julia-version: ${{ matrix.julia-version }}
